version: '3'

volumes:
  fitness_app_local_postgres_data: {}
  fitness_app_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: fitness_app_local_django
    container_name: fitness_app_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: fitness_app_production_postgres
    container_name: fitness_app_local_postgres
    volumes:
      - fitness_app_local_postgres_data:/var/lib/postgresql/data:Z
      - fitness_app_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: fitness_app_local_docs
    container_name: fitness_app_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./fitness_app:/app/fitness_app:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: fitness_app_local_redis

  celeryworker:
    <<: *django
    image: fitness_app_local_celeryworker
    container_name: fitness_app_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: fitness_app_local_celerybeat
    container_name: fitness_app_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: fitness_app_local_flower
    container_name: fitness_app_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  test:
    <<: *django
    command:
      test

  test-coverage:
    <<: *django
    command:
      test --cov-report term-missing --cov-report xml --cov=.

  local:
    <<: *django

  production:
    <<: *django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres