name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libpq-dev python-dev
        pip install -r requirements.txt
    - name: Create env file
      run: |
        cp .envs/.local/.django.example .django
        echo CELERY_FLOWER_PASSWORD= {{secrets.CELERY_FLOWER_PASSWORD }}>> .django
        echo CELERY_FLOWER_USER=${{ secrets.CELERY_FLOWER_USER }} >> .django
        echo IPYTHONDIR=${{ secrets.IPYTHONDIR }} >> .django
        echo USE_DOCKER=${{ secrets.USE_DOCKER }} >> .django
        echo REDIS_URL=${{ secrets.REDIS_URL }} >> .django
        cp .postgres.example .postgres
        cp .envs/.production/.django.example .django
        cp .envs/.production/.postgres.example .postgres
    - name: Build Container
      run: |
        docker-compose build
    - name: Run Tests
      run: |
        docker-compose run --rm test
